name: CI-SAST

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

    jobs:
      sast:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            language: [dotnet, node, python, java] # generic app support
     steps:
      - uses: actions/checkout@v4
        name: Run Semgrep (OWASP Top 10)
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/owasp-top-ten"

      # ---------------------------
      # 3. Trivy FS Scan (Dependency + SAST)
      # ---------------------------
      - name: Run Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          severity: "HIGH,CRITICAL"
          format: "table"
          output: "trivy-sast.txt"
          exit-code: "1"  # fail pipeline on critical issues

      # ---------------------------
      # 4. Upload Reports
      # ---------------------------
      - uses: actions/upload-artifact@v4
        with:
          name: sast-results-${{ matrix.language }}
          path: trivy-sast.txt
