    name: ZAP Baseline Scan

    on: [push]

    jobs:
      zap_scan:
        runs-on: ubuntu-latest
        name: Scan with OWASP ZAP
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: ZAP Baseline Scan
            uses: zaproxy/action-baseline@v0.12.0 # Use the latest version
            with:
              target: 'http://testphp.vulnweb.com/' # Replace with your target URL
              # Optional: Add other parameters like rulesFile, cmdOptions, etc.
