name: CI-Security-AI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # ----------------------
  # 1. Detect Language & Build/Test
  # ----------------------
 build-test:
    runs-on: ubuntu-latest
    outputs:
      lang: ${{ steps.detect.outputs.lang }}
    steps:
      - uses: actions/checkout@v4

      - name: Detect Application Language
        id: detect
        run: |
          if [ -f "pom.xml" ]; then
            echo "lang=java" >> $GITHUB_OUTPUT
          elif [ -f "package.json" ]; then
            echo "lang=node" >> $GITHUB_OUTPUT
          elif [ -f "requirements.txt" ]; then
            echo "lang=python" >> $GITHUB_OUTPUT
          elif ls *.sln >/dev/null 2>&1; then
            echo "lang=dotnet" >> $GITHUB_OUTPUT
          else
            echo "lang=unknown" >> $GITHUB_OUTPUT
          fi   # <-- this 'fi' was missing before

      - name: Run Unit Tests & Coverage
        run: |
          case "${{ steps.detect.outputs.lang }}" in
            java)
              mvn test
              echo "coverage-java.txt" > coverage-java.txt
              ;;
            node)
              npm install
              npm test
              echo "coverage-node.txt" > coverage-node.txt
              ;;
            python)
              pip install -r requirements.txt
              pytest --junitxml=coverage-python.txt
              ;;
            dotnet)
              dotnet test
              echo "coverage-dotnet.txt" > coverage-dotnet.txt
              ;;
            *)
              echo "No supported language detected"
              exit 1
              ;;
          esac   # <-- this 'esac' is required to close case

      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage-*.txt
          if-no-files-found: ignore

  # ----------------------
  # 2. SAST (Static Scans)
  # ----------------------
  sast:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run SAST Scans
        run: |
          if [ "${{ needs.build-test.outputs.lang }}" = "unknown" ]; then
            echo "Skipping SAST - no supported language"
            exit 0
          fi

          echo "Running Semgrep..."
          semgrep --config "p/owasp-top-ten" . || true

          echo "Running Trivy FS..."
          trivy fs --severity HIGH,CRITICAL --format table -o trivy-sast.txt .

      - uses: actions/upload-artifact@v4
        with:
          name: sast-results
          path: trivy-sast.txt
          if-no-files-found: ignore

  # ----------------------
  # 3. Container Security
  # ----------------------
  container-scan:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image & Scan
        run: |
          if [ "${{ needs.build-test.outputs.lang }}" = "unknown" ] || [ ! -f Dockerfile ]; then
            echo "Skipping container scan (no supported language or Dockerfile)"
            exit 0
          fi

          docker build -t myapp:${{ github.sha }} .
          trivy image --severity HIGH,CRITICAL --format table -o trivy-image.txt myapp:${{ github.sha }}

      - uses: actions/upload-artifact@v4
        with:
          name: container-results
          path: trivy-image.txt
          if-no-files-found: ignore

  # ----------------------
  # 4. AI Report for CI
  # ----------------------
  ai-ci:
    needs: [sast, container-scan]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: reports
      - uses: actions/download-artifact@v4
        with:
          name: sast-results
          path: reports
      - uses: actions/download-artifact@v4
        with:
          name: container-results
          path: reports

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
          ollama pull codellama

      - name: Collect CI Reports
        run: |
          echo "## Unit Test & Coverage (CI)" > ai-ci-input.md
          cat reports/coverage-*.txt >> ai-ci-input.md || true
          echo "## SAST Results" >> ai-ci-input.md
          cat reports/trivy-sast.txt >> ai-ci-input.md || true
          echo "## Container Scan" >> ai-ci-input.md
          cat reports/trivy-image.txt >> ai-ci-input.md || true

      - name: Generate AI CI Suggestions
        run: |
          cat ai-ci-input.md | ollama run codellama > ai-ci-suggestions.md

      - uses: actions/upload-artifact@v4
        with:
          name: ai-ci-suggestions
          path: ai-ci-suggestions.md
