name: SCA-Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sca-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Remove temp file if exists
        run: rm -f trivy_envs.txt || true

      - name: Run Trivy SCA Scan
        continue-on-error: true
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          severity: "HIGH,CRITICAL"
          format: "table"
          output: "trivy-sca.txt"
          exit-code: "1"

      - name: Upload SCA Report
        uses: actions/upload-artifact@v4
        with:
          name: sca-results
          path: trivy-sca.txt
